### ISSUE TITLE
Bad color rendering in production

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#56]
I tried to update our webserver plugin with the new Vue client but the rendering of colors is wrong.
In attachment a sample image. The same for Chrome and Firefox.

![build](https://user-images.githubusercontent.com/4079634/34778421-9551a21a-f61d-11e7-89cb-668d6b37316f.png)

**Comment by mcicolella** [comment]
@P3trur0 what about?

**Comment by P3trur0** [comment]
@mcicolella are you still having this issue? Which browser versions are you using? I can have a look next weekend.

**Comment by mcicolella** [comment]
@P3trur0 yes I'm still having the problem with latest Chrome and Firefox versions.

![bad_rendering](https://user-images.githubusercontent.com/4079634/35157337-f73c8752-fd33-11e7-803a-0a37fee6cedd.png)

**Comment by amenak77** [comment]
Hi, it is not a browser issue;  the interpreter renders correctly from cloned repo. The problem is either a conceptual bug about some element's project or more probably a compilation issue

**Comment by mcicolella** [comment]
Maybe [this](https://forum.vuejs.org/t/bad-color-rendering-in-production/26857/5) is a possible fix.

**Comment by mcicolella** [comment]
@P3trur0 what about the proposed fix in the previous comment?

**Comment by P3trur0** [comment]
@mcicolella we could give it a try.

**Comment by P3trur0** [comment]
Indeed, what suggested [here](https://forum.vuejs.org/t/bad-color-rendering-in-production/26857/5) is not a problem since Chrome does already support CSS properties.

Instead, this issue is fixed by properly overriding some CSS classes originally themed with a white background.

#132 should do the work.

**Comment by mcicolella** [comment]
@P3trur0 9f7eb0f04047e7e1fe4971eff54eb13bf012a691 didn't fix this. See images above.

**Comment by mcicolella** [comment]
Fixed with Quasar version.
